### ISSUE TITLE
Search for `Person.name` returns keyword error

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#2]
a search for eg "Klimt" in the "name or label" field of the person list returns:
Cannot resolve keyword 'label' into field choices are...
[search for "klimt"](https://oebl-pnp.acdh-dev.oeaw.ac.at/apis/entities/entity/person/list/?name=Klimt&start_date_written=&end_date_written=&first_name=&gender=&related_entity_name=&related_property_name=&Filter=Filter)

**Comment by b1rger** [comment]
this is due to the use of `name_label_filter` in https://github.com/acdh-oeaw/apis-core-rdf/blob/ff47d2aadf75cfe6936e5cc3a9f37ad9101f1cb1/apis_core/apis_entities/filters.py#L44

Maybe that line can simple be removed

**Comment by b1rger** [comment]
This was now fixed as part of https://github.com/acdh-oeaw/apis-core-rdf/pull/153 which is already deployed
