### ISSUE TITLE
import the missing XML files in the new instance

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#20]
currently there are not all published biographies in the APIS instance. We need to run through the XMLs in the share and
- import missing XMLs
- import missing old/newer versions of the same bios once the versioning is working -> https://github.com/acdh-oeaw/apis-core-rdf/pull/343 and https://github.com/acdh-oeaw/apis-core-rdf/issues/242
- when importing new XMLs (or new versions) we need to:
    - parse the complicated names into a main name and a list of alternative names
    - search the DB for place of birth and place of death, if there is no hit search geonames and/or other reference resources for the place names and create a new entry in the DB
    - parse the main biographical text for a) links to other XMLs (aka bios) and/or external links to other resources such as GND, deutsche Nationalbiographie and geo entries. Internal links should go into annotations, external ones need to be discussed

**Comment by b1rger** [comment]
1. Schritt: durch alle `*.xml` durch iterieren, schauen ob der `ÖBL 1815-1950, Bd. 1 (Lfg. 1, 1954), S. 1` text genauso in der DB existiert. Wenn das so ist, wurde das xml genauso importiert. Davon die Texte vergleichen und das xml für die weiteren schritte ignorieren.

**Comment by sennierer** [comment]
has been done, though there are bugs that need to be resolved
