### ISSUE TITLE
restructure the edit view for better usability

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#21]
curators need to have quick access to the important information, we therefore want to move the texts to the top ("Kurxinfo" should be first) and in the left panel move names, profession, gender and date of birth/death to the top.

**Comment by b1rger** [comment]
move up: gender, profession, first name
if possible: linked open date somewhere on top

**Comment by b1rger** [comment]
done in cc714e1e45ba08a3b0d906a7ee3c14c007186014
