### ISSUE TITLE
fix map vis in autocompletes

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#241]
currently `lat` and `long` in the autocompletes are in the format `XX,XX` while they should be `XX.XX` (proper float formatting)

**Comment by b1rger** [comment]
> currently `lat` and `long` in the autocompletes are in the format `XX,XX` while they should be `XX.XX` (proper float formatting)

lol, we now have `LANGUAGE_CODE = "de"` to have translations, but htis also formats floats differently ;)
