### ISSUE TITLE
change additional textfields to `null=True`

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#243]
the new text fields in the modle are not set to `null=True` which means that you need to set at least an empty string when creating new objects.

**Comment by b1rger** [comment]
This is because of https://docs.djangoproject.com/en/4.1/ref/models/fields/#null:

> Avoid using [null](https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.Field.null) on string-based fields such as [CharField](https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.CharField) and [TextField](https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.TextField). If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not NULL. One exception is when a [CharField](https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.CharField) has both unique=True and blank=True set. In this situation, null=True is required to avoid unique constraint violations when saving multiple objects with blank values.

**Comment by sennierer** [comment]
Ok, thanks...then we need to change the import scripts accordingly and we might want to change the other fields to remove `null=True` as well.
Closing this one.
