### ISSUE TITLE
select fields in list views render a huge list

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#3]
eg the "Profession" field in the person list view returns all (thousands) choices in one list (although there is a search field)

**Comment by b1rger** [comment]
we could replace it with a select2 field

**Comment by b1rger** [comment]
```
.dropdown-menu {         
  max-height: 200px;
  overflow-y: auto;
}
```

**Comment by sennierer** [comment]
great for other select fields, but occupations is to long, needs to go in a autocomplete -> see #16
