### ISSUE TITLE
in detail views the text field is showing the `django.object` rather than a string representation

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#4]
<django.contrib.contenttypes.fields.create_generic_related_manager.<locals>.GenericRelatedObjectManager object at 0x7ff944763710>

**Comment by b1rger** [comment]
same problem as #5 - i guess 'Texts` should not be listed in the info-table at all?

**Comment by b1rger** [comment]
Closing, as we are now defaulting to edit view
