### ISSUE TITLE
entity autocompletes are returning 500

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#6]
https://oebl-pnp.acdh-dev.oeaw.ac.at/apis/entities/autocomplete/institution/?q=Akademie

thats due to 
```shell
File "/home/vscode/.local/lib/python3.11/site-packages/apis_core/apis_entities/autocomplete3.py", line 163, in get
    for x in settings.APIS_ENTITIES[ent_model_name]["search"]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'search'
```

**Comment by b1rger** [comment]
This is fixed in acdh-oeaw/apis-core-rdf#322 - it now falls back to searching in all fields that are not relations
I've cherry-picked the PR into the `oebl-pnp` branch of `apis-core-rdf`
