### ISSUE TITLE
Fix different versions between xml and db

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-instance-oebl-pnp#62]
The differening strings that can *not* be explained by accents are listed in https://oeawcloud.oeaw.ac.at/index.php/s/pMzttM42k5RDqi6

**Comment by sennierer** [comment]
checking the first one on that list it seems that the main biographical and the short text between Adrian_Karl_1861_1949_resolved.xml and Adrian-Dussek_Eduard_1871_1930_resolved.xml have been switched in the resolved XMLs. @gregorpirgie can you please check and see if there might be an error in your script that caused this issue?

**Comment by gregorpirgie** [comment]
@b1rger @sennierer 

Have you checked the original xmls that my transformation was based on? I checked my old local files, and it seems that this error was already part of the xmls that where provided to me.

F.e. the "Kurzdefinition" of Adrian Karl in the input xml that I used for the transformation reads: 

```xml
<Kurzdefinition>Adrian-Dussek Eduard, Maler. * Klusso (Ungarn), um 1871; † Wien, 12. 11. 1930.</Kurzdefinition>
```

Here is the whole "Eintrag" section for Adrian Karl (this should be the untouched input xml):

```xml
<Eintrag Nummer="Adrian_Karl_1861_1949.xml">
   <Lexikonartikel>
      <Schlagwort>
         <Hauptbezeichnung>Adrian, </Hauptbezeichnung>
         <Nebenbezeichnung type="Vorname">Karl</Nebenbezeichnung>
      </Schlagwort>
      <Schlagwort_Nachname>Adrian</Schlagwort_Nachname>
      <Schlagwort_Vorname>Karl</Schlagwort_Vorname>
      <Vita>
         <Geburt Metadatum="1861">(1861-<Geographischer_Begriff>Salzburg (Sbg.)</Geographischer_Begriff>
         </Geburt>
         <Tod Metadatum="1949">1949)<Geographischer_Begriff>Salzburg (Sbg.)</Geographischer_Begriff>
         </Tod>
         <Berufsgruppe Berufsgruppe="Geisteswissenschaft">Volkskundler und Lehrer</Berufsgruppe>
         <Berufsgruppe Berufsgruppe="Unterrichtswesen"/>
      </Vita>
      <Lieferung Band="1" Seite="8">ÖBL 1815-1950, Bd. 1 (Lfg. 1, 1954), S. 8</Lieferung>
      <Kurzdefinition>Adrian-Dussek Eduard, Maler. * Klusso (Ungarn), um 1871; † Wien, 12. 11. 1930.</Kurzdefinition>
      <Haupttext>Stud. in Budapest Jus und nahm gleichzeitig bei den Prof. Lutz und Gregus Malunterricht, vollendete seine Ausbildung unter L’Allemand an der Wr. Akad. d. bild. Künste, dann in München und Paris; erhielt auf der Ausstellung des Dürerbundes 1909 den Ehrenpreis der Stadt Wien für ein Damenbildnis, 1910 die silberne, 1928 die goldene Medaille.</Haupttext>
      <Werk>W.: Abschied, 1911; Interieur, 1912; Vor dem Spiegel, 1913; St. Sebastian, 1928; etc.</Werk>
      <Literatur>L.: Wr.Ztg. vom 12. 11. 1930; A.Pr. vom 13. 11. 1930; R.P. vom 14. 11. 1930.</Literatur>
      <Autor/>
   </Lexikonartikel>
</Eintrag>
```

Can you verify that this is indeed the original file prior to the transformation?

**Comment by b1rger** [comment]
created a repo with the diff between db and xml version of the haupttexts: https://github.com/b1rger/oebldbxmldiff

**Comment by sennierer** [comment]
related to #20

**Comment by sennierer** [comment]
we now have all the version variants in place, including a script that harmonizes them
