### ISSUE TITLE
institutions view is missing relations to other institutions and places

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pnp#96]
in the original data we have relations like preceding institution https://apis.acdh.oeaw.ac.at/apis/entities/entity/institution/152447/detail

**Comment by b1rger** [comment]
Apperently we decided on those relations: https://github.com/acdh-oeaw/apis-instance-oebl-pnp/blob/main/apis_ontology%2Fmanagement%2Fcommands%2Frelations.py#L15

Are there others apart from institution-institution that are missing in this list?

**Comment by sennierer** [comment]
InstitutionInstitution is the only missing relationtype
